cloudscape-design/demos

- package-lock.json
In the mainline, lockfile was built for Nodejs 16, but our setup is still using 14. Resolve the mismatch by rebuilding it
---
> rebuild lockfile

- src/pages/form/form-unsaved-changes.index.jsx
- src/pages/non-console/non-console.index.jsx
n/a
This removes the explicit state handling of the side navigation and replaces it with the built-in state handling. This makes the side navigation automatically disappear on narrow viewports (such as mobile screens).
See also CR-78735274.
----
> Switch side navigation to uncontrolled state

- src/pages/dashboard/density-switch-images/comfortable-visual-refresh.jsx
- src/pages/dashboard/density-switch-images/common.jsx
- src/pages/dashboard/density-switch-images/compact-visual-refresh.jsx
- src/styles/density-switch-images.scss
This updates the preview SVGs that are shown in the "Density settings" dialog of the Dashboard demo. The table has a new header style, which needs to be reflected in these previews.
Compare also the `src/split-panel/icons` folder in [the components PR](https://github.com/cloudscape-design/components/pull/407/files), which does a similar change for the choice of split panel position, as well as CR-78870464.
------
> Update icons for density settings

- src/pages/edit/edit.index.jsx
- src/pages/form/components/cache-behavior-footer.jsx
- src/pages/form/components/distribution-panel.jsx
- src/pages/wizard/stepComponents/step2.jsx
- src/pages/wizard/stepComponents/step3.jsx
- src/pages/wizard/stepComponents/step4.jsx
Use `headerText` to replace `header` to align with API change from https://github.com/cloudscape-design/components/pull/473
> Use headerText instead of header in Expandablesection

- src/pages/onboarding/i18n.js
Add `labelTutorialListDownloadLink` and `labelLearnMoreLink props`, to allow aria-label on download link and learn more link. The labels were recently added by PR https://github.com/cloudscape-design/components/pull/534
> feat: Add arialabels to tutorial panel download and read more links

- package-lock.json
- scripts/check-package-lock.js
This change makes sure that the check-package-lock script works with the new package-lock.json format in npm v8. Its essentially equivalent to this PR: https://github.com/cloudscape-design/theming-core/pull/30
> chore: Update check-package-lock script to be compatible with npm v8

- test/e2e/page/tags-page-object.ts
*Issue #, if available:* n/a
*Description of changes:* Self-explanatory. `.findButton()` finds _any_ button, but we already have a better test util, `.findRemoveButton()`, available.
> chore: Use correct remove button test-util on tags page

- test/e2e/a11y.test.ts
Related to https://github.com/cloudscape-design/components/pull/800
Axe a11y rule doesn't allow any elements besides `<li>, <script> or <template>` as a direct children of `<ul>`.
However, separators with role=presentation inside list is still a valid markup, as they will be removed from a11y tree and therefore won't interrupt the list.
A11y team confirmed that it's a valid use-case.
> feat: Allow listitem to have role=presentation

- src/pages/delete-with-additional-confirmation/index.jsx
*Issue #, if available:* `CR-87372239`
Changed the "Confirm" form field and input in the Delete modal so that the Form field label uses the full width, but the input itself only uses 50% of the width.
The new label text caused the label to wrap in certain scenarios (e.g. in Visual Refresh), which is not desired. Instead, we only want the Input to have reduced width.
> chore: Stop delete confirmation label from wrapping

- test/e2e/details-tabs-template.test.ts
With the new sticky columns feature (https://github.com/cloudscape-design/components/pull/918), there is an increase in our sticky scrollbar z-index. It now overlaps the checkboxes and radio buttons in the table, which when trying to be clicked in the standard test's viewport size (1200*600), intercepts the click (see screenshot). This makes the test about clicking the first table item fail.
The solution presented here is to increase the window height by `200px` to avoid the scrollbar being on top of the targeted elements.
> chore: Increase details-tabs test window height

- src/i18n-strings/collection-preferences.ts
- src/i18n-strings/index.ts
- src/pages/commons/table-config.jsx
- src/pages/server-side-table-property-filter/index.jsx
- src/pages/server-side-table/index.jsx
- src/pages/split-panel-comparison/index.jsx
- src/pages/split-panel-comparison/table-config.jsx
- src/pages/split-panel-multiple/index.jsx
- src/pages/table-date-filter/index.jsx
- src/pages/table-date-filter/table-date-filter-config.jsx
- src/pages/table-editable/index.jsx
- src/pages/table-property-filter/property-filter-table.jsx
- src/pages/table-select-filter/index.jsx
- src/pages/table-select-filter/table-select-filter-config.jsx
- src/pages/table/index.jsx
- test/e2e/common/table/table-preferences-tests.ts
- test/e2e/page/table-page-object.ts
- test/e2e/table-select-filter.test.ts
This PR changes existing Table-related examples to use the new content display preference instead of the visible content display preference.
Additionally, it fixes two existing issues found along the way:
- In the table with date filter example,  a column was rendered in the table but not listed in the Collection preferences modal ([link](https://cloudscape.aws.dev/examples/react/table-date-filter.html))
- In the split panel examples, where a table is shown, the customization made in the collection preferences modal was not having effect on the table (see [here](https://cloudscape.design/examples/react/split-panel-multiple.html) and [here](https://cloudscape.design/examples/react/split-panel-comparison.html))
By submitting this pull request, I confirm that you …
> chore: Use Table column reordering

- src/pages/dashboard/widgets/service-overview/index.tsx
*Description of changes:* Use the new `minColumnWidth` property that was introduced for this use-case. See https://github.com/cloudscape-design/components/pull/1123.
> chore: Use new `minColumnWidth` property for Service overview widget

- .github/workflows/build.yml
Changes workflow to use NodeJS 18 for building. We're also upgrading the checkout action to v4 because it uses NodeJS 20 instead of 16: https://github.com/actions/checkout/releases/tag/v4.0.0. There is no version that uses NodeJS 18.
> chore: Upgrade workflows to NodeJS 18+

- src/pages/commons/common-components.tsx
- src/pages/dashboard/widgets/service-overview/index.tsx
- src/pages/split-panel-comparison/utils.jsx
*Description of changes:* These large number links in dashboard and split panel could use some additional context to improve their accessible name.
> chore: Add accessible names for large number-only links

- src/pages/non-console/index.jsx
*Issue #, if available:* CR-107566500
- Replaced the table in the non-console demo with a normal table in container, formatted with content layout. 
- Removed the content type so it doesn't go edge to edge from the recent updates.
Since we updated the page max width behavior in VR ([PR 1769](https://github.com/cloudscape-design/components/pull/1769)), we want to have a demo of a table that wouldn't use the full-page table pattern. This demo was the simplest standalone table which falls into that category. 
> chore: Replace full-page table with normal table in simple table demo

- src/pages/non-console/index.jsx
*Description of changes:* Removed superfluous attributes from profileActions. The types I removed do not exist on the `Item` interface, but do on the parent `Utility` interface. I believe they were included erroneously.
> Removed superfluous attributes from profileActions.

- src/pages/dashboard/widgets/instance-hours/index.tsx
- src/pages/dashboard/widgets/network-traffic/index.tsx
Update existing configurable dashboard demo to use our new API for chart drilldown features.
> feat: Showcase chart drill down features (links in keys and values)

- src/pages/table-editable/index.jsx
- src/pages/table/common-components.jsx
- test/e2e/page/table-page-object.ts
- test/e2e/table-editable.test.ts
*Issue #, if available:* `CR-108915214`
*Description of changes:* Add updated manual refresh pattern to the table inline edit demo.
> feat: Add updated manual refresh pattern to editable table

- src/styles/base.scss
Visual Design squad wants to add a bottom border to the demo header to visually separate it from the contents.
> chore: Add  bottom border to demo header

- test/e2e/page/table-editable-page-object.ts
Fixed a flaky test, see description in comments.
> fix: Fix flaky integration test for table with inline editing

- src/pages/commons/separated-list/styles.module.scss
Use newly introduced design token `color-border-divider-secondary` in Service homepage demo.
The new token is meant for horizontal dividers in tables, lists, etc.
> chore: Update list separator to use new design token

- src/common/property-filter-operators.ts
- src/fake-server/distributions.js
- src/pages/table-date-filter/table-date-filter-config.jsx
- src/pages/table-property-filter/table-property-filter-config.ts
- src/resources/distributionsFilteringProperties.json
- test/e2e/common/table/table-property-filtering-tests.ts
*Issue #, if available:* CR-116347209
Add new doesNotStartsWith operator in all property filters that use text comparison operators.
---
> feat: Add new 'does not start with' property filter operator to demos

- .github/workflows/build.yml
Addressing this comment: https://github.com/cloudscape-design/actions/pull/27#discussion_r1530742154
Make it easier to find all `npm install` instances
> chore: Use full npm command names

- src/pages/delete-one-click/index.jsx
- src/pages/split-panel-comparison/utils.jsx
- src/pages/table-saved-filters/index.jsx
- src/pages/table-select-filter/index.jsx
- src/pages/wizard/wizard-components.jsx
- src/styles/form.scss
- src/styles/product-page.scss
- src/styles/table-select.scss
- src/styles/top-navigation.scss
- src/styles/wizard.scss
- test/e2e/wizard-template.test.ts
*Issue #, if available:* N/A
*Description of changes:* Update with latest changes
> chore: Sync examples and demos

- test/e2e/common/table/table-property-filtering-tests.ts
- test/e2e/page/s3-page-object.ts
- test/e2e/page/table-property-filtering-page-object.ts
- test/e2e/s3-common.test.ts
- test/e2e/s3-read.test.ts
- test/e2e/table-saved-filters.test.ts
Preparing for changes to browser test tools: https://github.com/cloudscape-design/browser-test-tools/pull/107
Rel: CR-148624506
> chore: Updates integ tests for compatibility with webdriver upgrade

- src/fake-server/distributions.js
- src/pages/server-side-table-property-filter/index.jsx
- src/pages/table-date-filter/table-date-filter-forms.jsx
- src/pages/table-expandable/index.tsx
- src/pages/table-property-filter/property-filter-table.jsx
- src/pages/table-saved-filters/filter-set-modals.tsx
- src/pages/table-saved-filters/index.jsx
- src/pages/table-saved-filters/use-filter-sets.tsx
- src/styles/table-date-filter.scss
- test/e2e/table-saved-filters.test.ts
> chore: Updates property filter demos to feature token groups

- test/e2e/chat.test.ts
- test/e2e/page/chat-page-object.ts
This attempts to fix dry-run flakiness in e2e chat tests.
> chore: Add wait for prompt input before running chat tests

- src/pages/chat/common-components.tsx
- src/pages/chat/config.tsx
- src/pages/table-property-filter/property-filter-table.tsx
- src/pages/table-saved-filters/root.tsx
- src/styles/chat.scss
> chore: Import changes from the examples package

- src/pages/split-panel-comparison/table-config.tsx
- src/pages/split-panel-comparison/utils.tsx
Export demo updates for type and aria fixes in split panel demo. This fixes the failed demo test for https://github.com/cloudscape-design/components/pull/3492.
> chore: Export demo updates for type and aria fixes in split panel demo

- package.json
Until recently, we supported the latest three major versions of Safari.
This has changed. We do now support the latest three minor versions of Safari for macOS. This aligns with https://repost.aws/knowledge-center/browsers-management-console
Related links, issue #, if available: `AWSUI-60833`
> chore: Update supported Safari versions
