src/pages/delete/delete-one-click.index.jsx
src/pages/delete/delete-with-additional-confirmation.index.jsx
src/pages/delete/delete-with-simple-confirmation.index.jsx
src/pages/form/components/form-content.jsx
src/pages/form/form-unsaved-changes.index.jsx
src/pages/form/form-validation.index.jsx
src/pages/s3/common.jsx
src/pages/table/table-date-filter.index.jsx
src/pages/wizard/stepComponents/step2.jsx
src/pages/wizard/wizard.index.jsx

Reflecting the change made in https://github.com/cloudscape-design/components/pull/347

add missing alert aria labels

---

src/pages/wizard/wizard.index.jsx

*Issue #, if available:* N/A
*Description of changes:* See https://github.com/cloudscape-design/components/pull/357
I did this in the GitHub web editor! I love this website so much

chore(wizard): Add navigationAriaLabel to wizard demo

---

package-lock.json
package.json
webpack.config.js

https://github.com/cloudscape-design/demos/issues/11
This change adds support for launching the demos on Windows.
----

Enable launching on Windows

---

src/pages/table/table-property-filter-config.jsx

Updated placeholder text be inline with our guidelines.
See: AWSUI-19755, CR-79371858

chore: Update property filter placeholder text

---

src/pages/s3/read-from-s3.index.jsx
src/pages/s3/write-to-s3.index.jsx

*Issue #, if available:* AWSUI-19211
*Description of changes:* We have the exact text to use in our [writing guidelines](https://cloudscape.design/components/s3-resource-selector/?tabId=usage#writing-guidelines). Also, some things that aren't about the input format constraints should be moved to the description. 

chore: Update constraint text to follow writing guidelines

---

package-lock.json
package.json
webpack.config.js

This loader is not needed for our supported browsers

chore: Remove postcss loader

---

src/pages/onboarding/i18n.js

*Description of changes:* Update labelHotspot in demos corresponding to changes done in https://github.com/cloudscape-design/components/pull/507

feat: Update hotspot button arialabel with current and total steps

---

src/pages/split-panel/split-panel-comparison.index.jsx
src/pages/split-panel/split-panel-multiple.index.jsx
src/pages/split-panel/table-config.jsx
src/pages/table/property-filter-table.jsx
src/pages/table/server-side-table-property-filter.index.jsx
src/pages/table/server-side-table.index.jsx
src/pages/table/table-config.jsx
src/pages/table/table-date-filter-config.jsx
src/pages/table/table-select-filter.index.jsx
src/pages/table/table.index.jsx

**Changes Done**
Updating the table demos to include the new property stripedRows.
**Why?**
To show examples of the striped rows property in context.
**Testing**
Tested locally with all demos updated.
**Copy changes to CodeBrowser**
There's a twin CR in CodeBrowser for the internal demos as well: https://code.amazon.com/reviews/CR-81172456/revisions/1#/details

feat: Update table demos to include striped rows

---

.github/workflows/build.yml
package-lock.json
scripts/check-package-lock.js

AWSUI-19722
- Regenerate package-lock
- Upgrade workflows to v16

chore: Upgrade to Node16

---

examples-list.json
src/common/labels.js
src/pages/table/common-components.jsx
src/pages/table/table-config.jsx
src/pages/table/table-editable.index.jsx
test/e2e/cards-template.test.ts
test/e2e/common/flashbar-tests.ts
test/e2e/common/table/table-tests.ts
test/e2e/page/table-editable-page-object.ts
test/e2e/page/table-filtering-page-object.ts
test/e2e/page/table-page-object.ts
test/e2e/table-editable.test.ts
test/e2e/table-property-filter-server-side.test.ts
test/e2e/table-property-filter.test.ts
test/e2e/table-server-side.test.ts
test/e2e/table.test.ts

Porting CR-81943929 to open source demos

feat: add demo for table inline editing

---

package.json
src/common/clipboard.js
src/pages/onboarding/store.jsx

Fix existing linter errors and add lint script into CI workflow

fix linter errors

---

src/pages/table/table-config.jsx

Refactored code to match updated API for Table Inline Editing
Relevant PR: https://github.com/cloudscape-design/components/pull/636

refactor: Move edit mode cell render to separate function

---

.husky/commit-msg
.husky/pre-commit
.husky/prepare-commit-msg
package-lock.json
package.json

Husky dependency was installed, but no hooks configured. Fixed this now by copying the hooks from `cloudscape-design/components` repository

setup git hooks

---

src/common/i18nStrings.js
src/common/s3-resource-selector/i18n-strings.js
src/pages/cards/index.jsx
src/pages/delete-with-additional-confirmation/instances-table.jsx
src/pages/delete-with-simple-confirmation/distributions-table.jsx
src/pages/details-tabs/index.jsx
src/pages/form/components/distribution-panel.jsx
src/pages/form/components/headers-editor.jsx
src/pages/form/components/origin-panel.jsx
src/pages/non-console/index.jsx
src/pages/server-side-table/index.jsx
src/pages/split-panel-comparison/index.jsx
src/pages/split-panel-multiple/index.jsx
src/pages/table-editable/index.jsx
src/pages/table-property-filter/table-property-filter-config.jsx
src/pages/table-select-filter/index.jsx
src/pages/table/index.jsx
src/pages/table/table-config.jsx

*Description of changes:* Added the _just_ released clear aria labels to the demos

chore: Add input clear aria labels to demos

---

src/pages/delete-with-additional-confirmation/index.jsx
src/pages/delete-with-simple-confirmation/index.jsx

Related CR: CR-86050458
Update the delete pattern texts, to better adhere to our content style guide.

chore: Update delete pattern texts

---

test/e2e/a11y.test.ts

Implementation of the side navigation was changed, so it should not be an issue any more.

revert: Allow listitem to have role=presentation (#50)

---

src/pages/table-select-filter/index.jsx
src/styles/table-select.scss

*Issue #, if available:* 
*Description of changes:* Port of CR-87387297

fix: Announce filtering results in table select filter demo

---

webpack.config.js

Fixing a configuration error added in https://github.com/cloudscape-design/demos/pull/59

fix dev server configuration

---

src/pages/commons/separated-list/styles.module.scss
src/pages/configurable-dashboard/components/palette-item/styles.module.scss
src/pages/dashboard/components/density-preferences/images/styles.module.scss
src/pages/dashboard/components/empty-state/styles.module.scss
src/pages/dashboard/widgets/base-static-widget/styles.module.scss
src/pages/dashboard/widgets/operational-metrics/preferences.module.scss
src/pages/form/components/cache-behavior-panel.jsx
src/pages/wizard/stepComponents/step4.jsx
src/styles/form.scss
src/styles/onboarding.scss
src/styles/table-date-filter.scss
src/styles/table-select.scss
src/styles/wizard.scss

Auto-export of CR-88880994.
I could remove the unrelated changes, but that probably means the next person to run the exporter will have to deal with them, so...

fix: Update wizard review step headers to be semantically correct

---

src/pages/form/components/distribution-panel.jsx
src/pages/form/components/tools-content.tsx

chore: Add file upload to form demo

---

src/pages/form/components/distribution-panel.jsx

chore: Use terminal punctuation for file upload demo

---

src/pages/commons/table-config.jsx
src/pages/server-side-table-property-filter/index.jsx
src/pages/server-side-table/index.jsx
src/pages/split-panel-comparison/index.jsx
src/pages/split-panel-multiple/index.jsx
src/pages/table-editable/index.jsx
src/pages/table-property-filter/property-filter-table.jsx
src/pages/table-select-filter/index.jsx
src/pages/table/index.jsx

*Issue #, if available:* CR-88810247
*Description of changes:* Added sticky columns preferences to demos.

feat: Add sticky columns to demos

---

src/i18n-strings/property-filter.ts
src/i18n-strings/table.ts
src/pages/commons/table-config.jsx
src/pages/dashboard/components/side-navigation.tsx
src/pages/form/components/form-content.jsx
src/pages/split-panel-multiple/index.jsx
src/pages/table-select-filter/index.jsx
src/styles/table-select.scss

Export all recent demo updates in this repository

export demo updates

---

package-lock.json

*Issue #, if available:* AWSUI-21117
*Description of changes:* Bumped yaml to solve security issue.

chore: Bumb yaml from 2.2.1 to 2.2.2

---

src/pages/dashboard/widgets/service-overview/index.tsx

*Issue #, if available:* CR-92236323

chore: Update column layout for service overview widget

---

src/pages/split-panel-comparison/utils.jsx

*Issue #, if available:* 
Remove usage of deprecated embedded table variant, because we want to show customers how to do it properly.

chore: Remove usage of deprecated embedded table variant

---

src/pages/cards/index.jsx
src/pages/details-hub/index.jsx
src/pages/details-tabs/index.jsx
src/pages/details/common-components.jsx
src/pages/server-side-table-property-filter/index.jsx
src/pages/server-side-table/index.jsx
src/pages/table-date-filter/index.jsx
src/pages/table-editable/index.jsx
src/pages/table-property-filter/index.jsx
src/pages/table-property-filter/property-filter-table.jsx

*Issue #, if available:* CR-92714480
Fixed the implementation according to our guidelines

chore: hide table counters when resources are loading

---

src/pages/onboarding/help-panel-content.jsx
src/pages/onboarding/subpages/create-transcription-job.jsx
src/pages/wizard/steps-config.jsx

Remove links within form control descriptions, to avoid nested interactive elements

fix: Remove links within form control descriptions

---

src/pages/details/common-components.jsx

See doc lBEiAjMoigz3
Adding searching and sorting to improve UX for tag tables with many tags.

chore: Add searching and sorting to the tags table demo

---

src/pages/commons/table-config.jsx
test/e2e/common/table/table-preferences-tests.ts
test/e2e/page/table-editable-page-object.ts
test/e2e/table-editable.test.ts

*Issue #, if available:* `CR-95704770`
*Description of changes:* Adding table in-context actions to the table demos.

chore: Add table in-context actions

---

src/common/localStorage.ts
src/common/types.ts

chore: Add cookieConsent for saving to local storage

---

setupJest.js
src/pages/dashboard/components/side-navigation.tsx
src/pages/dashboard/widgets/account-attributes/index.tsx
src/pages/dashboard/widgets/alarms/index.tsx
src/pages/dashboard/widgets/events/index.tsx
src/pages/dashboard/widgets/features-spotlight/index.tsx
src/pages/dashboard/widgets/instance-limits/index.tsx
src/pages/onboarding/subpages/transcription-job-details.jsx
src/pages/onboarding/tutorial-data.jsx
test/e2e/page/form-page-object.ts

chore: Export updated demos content

---

examples-list.json
src/pages/table-saved-filters/filter-set-modals.tsx
src/pages/table-saved-filters/index.jsx
src/pages/table-saved-filters/use-filter-sets.tsx
test/e2e/page/table-property-filtering-page-object.ts
test/e2e/page/table-saved-filters-page-object.ts
test/e2e/table-saved-filters.test.ts

chore: Add demo for saved filter set pattern

---

test/e2e/s3-common.test.ts

Account for the change in: https://github.com/cloudscape-design/components/pull/1737

chore: make s3 i18n assertion more loose

---

src/pages/dashboard/index.tsx
src/pages/form-validation/index.jsx
src/pages/wizard/steps-config.jsx

chore: Remove unused imports

---

src/pages/delete-one-click/index.jsx

chore: Move alert to header to align with other demos

---

src/pages/table-editable/index.jsx
src/pages/table/common-components.jsx

*Issue #, if available:* https://github.com/cloudscape-design/components/issues/1623

chore: Update inline editing demo to disable actions while saving

---

test/e2e/page/table-editable-page-object.ts

Updating selected used in tests to unblock https://github.com/cloudscape-design/components/pull/1906

chore: Fix table inline editing submit button selector

---

src/pages/commons/table-config.jsx

*Issue #, if available:* `CR-111850047`
*Description of changes:* Adjust table inline edit demo for the new `disabledReason` property.

chore: Add `disabledReason` feature to table inline edit demo

---

src/pages/dashboard/widgets/alarms/index.tsx
src/pages/dashboard/widgets/events/index.tsx
src/pages/dashboard/widgets/instance-limits/index.tsx
src/pages/delete-with-additional-confirmation/instances-table.jsx
src/pages/delete-with-simple-confirmation/distributions-table.jsx
src/pages/details-hub/index.jsx
src/pages/details-tabs/index.jsx
src/pages/details/common-components.jsx
src/pages/non-console/index.jsx
src/pages/onboarding/subpages/transcription-job-list.jsx
src/pages/server-side-table-property-filter/index.jsx
src/pages/server-side-table/index.jsx
src/pages/split-panel-comparison/index.jsx
src/pages/split-panel-comparison/utils.jsx
src/pages/split-panel-multiple/index.jsx
src/pages/table-editable/index.jsx
src/pages/table-property-filter/property-filter-table.jsx
src/pages/table-saved-filters/index.jsx
src/pages/table-select-filter/index.jsx
src/pages/table/index.jsx

Use enableKeyboardNavigation in all demo tables.
Rel: CR-114599335

chore: Use table keyboard navigation in all tables

---

src/pages/product-detail-page/index.tsx

chore: Minor fixes for product page

---

package-lock.json
package.json
src/pages/details/common-components.jsx
src/pages/details/details-code-snippets.js
src/pages/details/index.jsx

*Issue #, if available:* CR-112019660
Added a "Distribution configuration details" container to the Details page demo, featuring the new code view component.

feat: Add code view component to details page

---

src/i18n-strings/pagination.ts

A fix for https://github.com/cloudscape-design/components/pull/2166

fix: Update renderAriaLive to accept missing total

---

src/pages/edit/index.jsx
src/pages/form-unsaved-changes/index.jsx
src/pages/form-validation/index.jsx
src/pages/form/components/form.jsx
src/pages/form/index.jsx
src/pages/non-console/index.jsx
src/pages/onboarding/subpages/create-transcription-job.jsx
src/pages/read-from-s3/index.jsx
src/pages/write-to-s3/index.jsx
test/e2e/edit-template.test.ts
test/e2e/form-template.test.ts
test/e2e/form-validation.test.ts
test/e2e/page/edit-form-page-object.ts
test/e2e/page/form-page-object.ts
test/e2e/page/s3-page-object.ts
test/e2e/s3-read.test.ts
test/e2e/s3-write.test.ts

chore: Remove unnecessary ContentLayout usage

---

src/pages/form/components/cache-behavior-footer.jsx
src/pages/form/components/cache-behavior-panel.jsx
src/pages/form/components/distribution-panel.jsx
src/pages/form/components/form.jsx
src/pages/form/components/headers-editor.jsx
src/pages/form/components/origin-panel.jsx
src/pages/form/components/tags-panel.jsx
src/pages/form/form-validation-config.tsx
test/e2e/form.test.ts
test/e2e/page/form-page-object.ts

This PR updates form validation demo to address fast follow items for validation improvements.
Refer to CR-123650230 for more context.

chore: Update form validation demo - validation improvements fast follows

---

src/pages/wizard/stepComponents/step2.jsx
src/pages/wizard/utils.js
src/styles/wizard.scss

Adding slider to step 2 of the wizard demo, as part of the slider component release.

feat: Adds slider to wizard demo step 2

---

src/pages/form/components/headers-editor.jsx
src/pages/form/components/origin-panel.jsx
src/pages/form/form-validation-config.tsx
test/e2e/form-validation.test.ts
test/e2e/page/form-page-object.ts

AWSDesignSystem-429
Added warning validation to form validation demo.

feat: Add warning validation to form validation demo

---

src/pages/configurable-dashboard/app.tsx
src/pages/configurable-dashboard/components/page-banner.tsx
src/pages/dashboard/index.tsx
src/pages/delete-one-click/index.jsx
src/pages/delete-with-additional-confirmation/index.jsx
src/pages/delete-with-simple-confirmation/index.jsx
src/pages/details-hub/index.jsx
src/pages/details-tabs/index.jsx
src/pages/details/index.jsx
src/pages/manage-tags/index.jsx
src/pages/onboarding/subpages/transcription-job-details.jsx
src/pages/product-detail-page/hero-header.tsx
src/pages/product-detail-page/index.tsx
src/styles/product-page.scss

feat: Update demos to reflect content layout changes

---

src/pages/dashboard/components/density-preferences/images/comfortable-visual-refresh.tsx
src/pages/dashboard/components/density-preferences/images/compact-visual-refresh.tsx

chore: Remove high-contrast header in density settings

---

src/pages/non-console/index.jsx

Currently incorrect: https://cloudscape.design/examples/react/non-console.html

fix: Update content spacing in top navigation demo

---

package-lock.json
src/common/adjust-body-padding.js
src/pages/form/form-validation-config.tsx
src/pages/table-expandable/index.tsx
test/e2e/common/base-example-page.ts
test/e2e/configurable-dashboard.test.ts
test/e2e/details-tabs.test.ts
test/e2e/details.test.ts
test/e2e/page/app-layout-page-object.ts
test/e2e/page/details-hub-page-object.ts
test/e2e/page/edit-form-page-object.ts
test/e2e/page/form-page-object.ts
test/e2e/page/form-template-page-object.ts
test/e2e/page/product-page-page-object.ts
test/e2e/page/s3-page-object.ts
test/e2e/page/tags-page-object.ts
test/e2e/page/wizard-page-object.ts
test/e2e/product-page.test.ts
test/e2e/table-expandable.test.ts
webpack.config.js

Synchronised internal examples with demos using automated script. This brings updates to expandable table demo and some more changes.

chore: Sync examples and demos

---

package-lock.json
package.json
src/pages/dashboard/widgets/operational-metrics/index.tsx
src/pages/dashboard/widgets/service-overview/index.tsx
src/pages/delete-with-additional-confirmation/index.jsx
src/pages/details/common-components.jsx
src/pages/onboarding/subpages/transcription-job-details.jsx
src/pages/split-panel-comparison/utils.jsx
src/pages/table-saved-filters/filter-set-modals.tsx
src/pages/wizard/stepComponents/step4.jsx

These changes were exported from `AWS-UI-Examples` repo

chore: Replace Key-value pairs entries with a new component

---

package-lock.json
tsconfig.json

Ran `npm audit fix` to fix this dependabot issue: https://github.com/cloudscape-design/demos/security/dependabot/29

chore: Updrade dependencies

---

src/pages/table-date-filter/table-date-filter-forms.jsx

Demo changes to match updated guidelines on property filter custom forms. Synced with [CR-142908163].

chore: Update property filter custom form demo

---

src/pages/table-saved-filters/use-filter-sets.tsx
test/e2e/details-tabs.test.ts
test/e2e/page/tags-page-object.ts

chore: Updates e2e tests to support webdriverio 9 changes

---

src/common/property-filter-operators.ts
src/pages/table-date-filter/table-date-filter-config.jsx
src/pages/table-expandable/index.tsx
src/pages/table-expandable/table-configs.tsx
src/pages/table-property-filter/table-property-filter-config.ts

Demos for https://github.com/cloudscape-design/components/pull/2626 and https://github.com/cloudscape-design/components/pull/2739

chore: Demos for property filter groups and multi-select tokens

---

src/pages/dashboard/components/empty-state/styles.module.scss
src/pages/table-expandable/index.tsx
src/pages/table-select-filter/index.jsx
src/pages/table/common-components.jsx
test/e2e/page/table-page-object.ts

Pull latest content from the upstream source

chore: Export latest content

---

setupJest.js
test/e2e/page/chat-page-object.ts

Attempted to fix chat tests failures in dry-run and added retries (same as in main repo).

chore: Attempt fixing chat e2e tests

---

test/e2e/chat.test.ts
test/e2e/page/chat-page-object.ts

chore: Disables e2e test for chat

---

test/e2e/chat.test.ts

chore: Skip chat tests

---

.github/workflows/close-stale-issues.yml

Add automation to close issues left without a response for too long

add stale issues workflow

---

src/pages/chat/chat.tsx
src/pages/chat/common-components.tsx
src/pages/chat/config.tsx
src/pages/chat/messages.tsx
src/styles/chat.scss

Updates the chat demo with file upload and support prompts functionality.

feat: Update chat demo with file upload and support prompts

---

package-lock.json
package.json

Webdriver is a transient dependency that comes from browser-test-tools and it should not be installed explicitly.
Rel: CR-180493765

chore: Fixes package dependencies

---

package-lock.json
src/pages/configurable-dashboard/i18n-strings.ts
test/e2e/common/base-example-page.ts
test/e2e/details-tabs.test.ts
test/e2e/details.test.ts
test/e2e/page/cards-page-object.ts
test/e2e/page/delete-with-confirmation-page-object.ts
test/e2e/page/table-editable-page-object.ts
test/e2e/page/table-page-object.ts
test/e2e/page/table-property-filtering-page-object.ts
test/e2e/page/tags-page-object.ts
test/e2e/s3-read.test.ts

export demos updates

---

src/pages/commons/notifications.tsx
src/pages/form-validation/app.tsx
src/pages/form/app.tsx
src/pages/form/components/cache-behavior-panel/cache-behavior-footer.tsx
src/pages/form/components/cache-behavior-panel/cache-behavior-panel.tsx
src/pages/form/components/cache-behavior-panel/cache-key-origin-settings.tsx
src/pages/form/components/cache-behavior-panel/create-cache-policy.tsx
src/pages/form/components/cache-behavior-panel/origin-request-policy.tsx
src/pages/form/components/cache-behavior-panel/use-create-cache-policy.ts
src/pages/form/components/distribution-panel.tsx
src/pages/form/components/form.tsx
src/pages/form/components/origin-panel.tsx
src/pages/form/components/tags-panel.tsx
src/pages/form/components/tools-content.tsx
src/pages/form/components/unsaved-changes-modal.tsx
src/pages/form/form-config.ts
src/pages/form/form-validation-config.ts
src/pages/form/types.ts
test/e2e/common/base-example-page.ts
test/e2e/common/flashbar-tests.ts
test/e2e/form-template.test.ts
test/e2e/form-validation.test.ts
test/e2e/form.test.ts
test/e2e/page/app-layout-page-object.ts
test/e2e/page/form-page-object.ts
test/e2e/page/form-template-page-object.ts

*Issue #:* AWSUI-14600, CR-176481157
*Description of changes:* Updated form and form validation demos for sub-resource creation

feat: Sub-resource creation in form and form validation demos

---

scripts/generate-html-files.js

This class was removed when mass-importing changes in https://github.com/cloudscape-design/demos/pull/194
Need to put it back

chore: Restore missing class

---

jest.config.js
package.json
scripts/dev-server.js
scripts/generate-html-files.js
src/pages/commons/common-components.tsx
src/pages/configurable-dashboard/app.tsx
src/pages/configurable-dashboard/widgets.ts
src/pages/dashboard/components/content.tsx
src/pages/dashboard/widgets/index.ts
test/e2e/common/base-example-page.ts
test/e2e/configurable-dashboard.test.ts
test/e2e/form-validation.test.ts
test/e2e/form.test.ts
test/e2e/product-page.test.ts
test/e2e/utils.ts
test/e2e/wizard-template.test.ts
webpack.config.mjs

Updated export of changes to demo repository.
Fixes https://github.com/cloudscape-design/demos/issues/197

chore: Export demo updates
